### ISSUE TITLE
Youtube api

### ISSUE THREAD

**Issue by mrhussnain** [KaustubhPatange/YTPlayer#1]
where to change youtube api??

**Comment by KaustubhPatange** [comment]
Didn't get your question! Could you elaborate it?

**Comment by mrhussnain** [comment]
i mean where to change YouTube data api v3??

**Comment by KaustubhPatange** [comment]
@mrhussnain This is not based on Youtube Data Api. Since it has quota limits I created my own API to do some YouTube analytic tasks (explained in repo's wiki page).

**Comment by mrhussnain** [comment]
so what is the limit per day?

**Comment by mrhussnain** [comment]
and one thing more where to change admob???

**Comment by KaustubhPatange** [comment]
@mrhussnain Unlimited i.e no limit

**Comment by KaustubhPatange** [comment]
@mrhussnain Change admob IDs in respective classes recursively. They are not defined in strings.xml.

**Comment by mrhussnain** [comment]
where to change admob idz?

**Comment by mrhussnain** [comment]
heaving issue with this video not able to download/play 
https://youtu.be/vKDsAB1ccn0
can you please check

**Comment by KaustubhPatange** [comment]
@mrhussnain Problem with this api https://github.com/HaarigerHarald/android-youtubeExtractor create an issue there!
