### ISSUE TITLE
github library error

### ISSUE THREAD

**Issue by mrhussnain** [KaustubhPatange/YTPlayer#2]
ERROR: Could not determine artifacts for com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT:53a52aa96f-1: Skipped due to earlier error

ERROR: Could not determine artifacts for com.github.jgabrielfreitas:BlurImageView:1.0.1: Skipped due to earlier error

please help me to resolve

**Comment by KaustubhPatange** [comment]
Use latest Android Studio with gradle 4.0 or higher.

Try com.github.HaarigerHarald:android-youtubeExtractor:1.9.0
 
com.github.jgabrielfreitas:BlurImageView:1.3.3

**Comment by mrhussnain** [comment]
okay thank you so much i will try this and let you know if any issue occurred really you have did amazing work.

**Comment by mrhussnain** [comment]
after updating it shows this error

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.jgabrielfreitas:BlurImageView:1.3.3.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.evgenyneu:js-evaluator-for-android:v4.0.0.
Show Details
Affected Modules: app

**Comment by KaustubhPatange** [comment]
Post the issue in the respective github library's repo. Sure they will help you! Its working for me coz maybe i've synced it already!

**Comment by mrhussnain** [comment]
please send me the link where to post??

**Comment by mrhussnain** [comment]
or can you please share the latest code that you have

**Comment by KaustubhPatange** [comment]
You are developer and you don't know how to find library's repo!

**Comment by mrhussnain** [comment]
opps i am noob
