### ISSUE TITLE
search result

### ISSUE THREAD

**Issue by mrhussnain** [KaustubhPatange/YTPlayer#5]
how to increase the search result currently it is just showing 6 items

**Comment by KaustubhPatange** [comment]
Can't increase! That's what the result api returns. Since its a hack based on YouTube results it only provides you top 6 results only!

**Comment by mrhussnain** [comment]
i think this lib helps you to update it is extracting all songs

https://github.com/naveedhassan913/YouTubeExtractor

**Comment by mrhussnain** [comment]
i need help to implement this lib

**Comment by KaustubhPatange** [comment]
Yea this is extracting everything! I will see to implement it soon currently busy with some other stuff.

**Comment by mrhussnain** [comment]
oh  thanks one thing more are you available as a freelancer??

**Comment by KaustubhPatange** [comment]
I am

**Comment by mrhussnain** [comment]
please check...
