### ISSUE TITLE
Request loop system

### ISSUE THREAD

**Issue by chiqors** [KaustubhPatange/YTPlayer#7]
I don't see any icon/button to activate loop.. i saw something like it.. when i checked only 1 music and repeat mode on.. but it didn't work

**Comment by KaustubhPatange** [comment]
Will soon fix it.

**Comment by chiqors** [comment]
![Screenshot_YTPlayer_20200203-124128](https://user-images.githubusercontent.com/13832788/73628387-b1bf0480-4682-11ea-89fa-5551020e24df.png)
![Screenshot_YTPlayer_20200203-124140](https://user-images.githubusercontent.com/13832788/73628390-b2579b00-4682-11ea-8e66-1f8ddb31e1b6.png)
I thought this was a repeat icon.. and i checked only 1 music.. i thought it was only 1 song will repeat.. but it's not

**Comment by KaustubhPatange** [comment]
This repeat will repeat your playlist not the song so those two song will
be repeated. You can remove the song from there and then apply repeat

**Comment by chiqors** [comment]
But, it's bothering me.. imagine if there are many songs in queue and i had to delete all of them for a single song i want to loop

**Comment by KaustubhPatange** [comment]
Will add this feature soon in an update!
